version: '3.8'

services:
  web:
    build: .
    container_name: web_part
    volumes:
      - .:/fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      - database

  database:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"


volumes:
  postgres_data:
